FROM eosio/builder as ncc
ARG cxpbranch

RUN git clone -b $cxpbranch https://rcfcu2000:Video0me!@github.com/rcfcu2000/ncc.git

FROM ubuntu:18.04

RUN apt-get -y update \
    && apt-get -y dist-upgrade \
		&& apt install --reinstall software-properties-common \
		&& add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" \
		&& apt-get -y update \
    && apt-get -y dist-upgrade \    && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl ca-certificates \
    && apt-get -y install libicu55 wget \
    && wget https://github.com/eosio/eos/releases/download/v1.8.1/eosio_1.8.1-1-ubuntu-16.04_amd64.deb \
    && apt-get -y install ./eosio_1.8.1-1-ubuntu-16.04_amd64.deb \
    && wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.5.0/eosio.cdt_1.5.0-1_amd64.deb \
    && apt-get -y install ./eosio.cdt_1.5.0-1_amd64.deb \
    && apt-get -y install nodejs \
    && apt-get -y install npm \
    && apt-get -y install git \
    && apt-get -y install vim \
    && rm -rf /var/lib/apt/lists/*
    
# Copy and buid coinxp contracts
COPY --from=ncc /ncc/contracts /coinxp/contracts/
COPY --from=ncc /ncc/services/secretmgr /coinxp/services/secretmgr

ENV EOSIO_ROOT=/opt/eosio
RUN chmod +x /opt/eosio/bin/nodeosd.sh
ENV LD_LIBRARY_PATH /usr/local/lib
ENV PATH /opt/eosio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Build coinxp contracts
RUN cd /coinxp/services/secretmgr \
    && npm install \
    && cd /coinxp/contracts/scripts \
    && ./build_contracts.sh \
    && mkdir -p /opt/eosio/bin/data-dir/wallet
