const char* const address_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-08T08:03:54",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "tokenmap_s",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "tokenSymbol",
          "type": "uint64"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "contractaddr",
          "type": "string"
        },{
          "name": "symbol",
          "type": "uint64"
        }
      ]
    },{
      "name": "oracle_rec",
      "base": "",
      "fields": [{
          "name": "username",
          "type": "name"
        }
      ]
    },{
      "name": "address_rec",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "address",
          "type": "string"
        },{
          "name": "creator",
          "type": "name"
        },{
          "name": "assignee",
          "type": "name"
        },{
          "name": "is_valid",
          "type": "bool"
        },{
          "name": "txhash",
          "type": "string"
        },{
          "name": "approvers",
          "type": "name[]"
        },{
          "name": "rejecters",
          "type": "name[]"
        }
      ]
    },{
      "name": "address_stat",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "num_total",
          "type": "uint64"
        },{
          "name": "num_valid",
          "type": "uint64"
        },{
          "name": "num_assigned",
          "type": "uint64"
        }
      ]
    },{
      "name": "add",
      "base": "",
      "fields": [{
          "name": "creator",
          "type": "name"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "address",
          "type": "string"
        },{
          "name": "txhash",
          "type": "string"
        }
      ]
    },{
      "name": "approve",
      "base": "",
      "fields": [{
          "name": "approver",
          "type": "name"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "address",
          "type": "string"
        }
      ]
    },{
      "name": "reject",
      "base": "",
      "fields": [{
          "name": "rejecter",
          "type": "name"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "address",
          "type": "string"
        }
      ]
    },{
      "name": "assign",
      "base": "",
      "fields": [{
          "name": "assignee",
          "type": "name"
        },{
          "name": "token",
          "type": "string"
        }
      ]
    }
  ],
  "actions": [{
      "name": "add",
      "type": "add",
      "ricardian_contract": ""
    },{
      "name": "approve",
      "type": "approve",
      "ricardian_contract": ""
    },{
      "name": "reject",
      "type": "reject",
      "ricardian_contract": ""
    },{
      "name": "assign",
      "type": "assign",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "tokens",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "tokenmap_s"
    },{
      "name": "oracles",
      "index_type": "i64",
      "key_names": [
        "username"
      ],
      "key_types": [
        "name"
      ],
      "type": "oracle_rec"
    },{
      "name": "addresses",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "address_rec"
    },{
      "name": "addrstat",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "address_stat"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
