const char* const coinxp_api_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-08T08:05:28",
  "version": "eosio::abi/1.0",
  "types": [{
      "new_type_name": "symbol_name",
      "type": "uint64"
    }
  ],
  "structs": [{
      "name": "OrderDb",
      "base": "",
      "fields": [{
          "name": "request_id",
          "type": "uint64"
        },{
          "name": "orderbook_key",
          "type": "uint64"
        },{
          "name": "scope",
          "type": "uint64"
        },{
          "name": "currency_symbol",
          "type": "symbol_name"
        },{
          "name": "commodity_symbol",
          "type": "symbol_name"
        },{
          "name": "is_buy",
          "type": "bool"
        },{
          "name": "traded_currency",
          "type": "uint64"
        },{
          "name": "traded_commodity",
          "type": "uint64"
        },{
          "name": "price",
          "type": "uint64"
        },{
          "name": "pending_commodity",
          "type": "uint64"
        },{
          "name": "status",
          "type": "uint16"
        },{
          "name": "timestamp",
          "type": "uint64"
        }
      ]
    },{
      "name": "cancel",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "request_key",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "cancel",
      "type": "cancel",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "orderdb",
      "index_type": "i64",
      "key_names": [
        "request_id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "OrderDb"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
