const char* const coinxp_exchange_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-21T03:27:21",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "account_asset",
      "base": "",
      "fields": [{
          "name": "balance",
          "type": "asset"
        },{
          "name": "locked",
          "type": "asset"
        },{
          "name": "frozen",
          "type": "bool"
        }
      ]
    },{
      "name": "currency",
      "base": "",
      "fields": [{
          "name": "supply",
          "type": "asset"
        }
      ]
    },{
      "name": "trading_fee",
      "base": "",
      "fields": [{
          "name": "exchangefee",
          "type": "asset"
        }
      ]
    },{
      "name": "bank_fee",
      "base": "",
      "fields": [{
          "name": "bankfee",
          "type": "asset"
        },{
          "name": "exchange",
          "type": "name"
        }
      ]
    },{
      "name": "CoinPair",
      "base": "",
      "fields": [{
          "name": "currency",
          "type": "symbol_code"
        },{
          "name": "commodity",
          "type": "symbol_code"
        },{
          "name": "timestamp",
          "type": "uint64"
        }
      ]
    },{
      "name": "cxp_rate",
      "base": "",
      "fields": [{
          "name": "supply",
          "type": "asset"
        }
      ]
    },{
      "name": "order_fee",
      "base": "",
      "fields": [{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "banklocked",
          "type": "int64"
        },{
          "name": "exchangelocked",
          "type": "int64"
        }
      ]
    },{
      "name": "acc_frozen",
      "base": "",
      "fields": [{
          "name": "auto_key",
          "type": "uint64"
        },{
          "name": "frozen",
          "type": "bool"
        }
      ]
    },{
      "name": "lock",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "unlock",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "subbalance",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        }
      ]
    },{
      "name": "sublocked",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "addbalance",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "lockx",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "unlockx",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "sublockedx",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "addbalancex",
      "base": "",
      "fields": [{
          "name": "owner",
          "type": "name"
        },{
          "name": "value",
          "type": "asset"
        },{
          "name": "orderid",
          "type": "uint64"
        },{
          "name": "full",
          "type": "bool"
        }
      ]
    },{
      "name": "createfee",
      "base": "",
      "fields": [{
          "name": "fee",
          "type": "asset"
        }
      ]
    },{
      "name": "removefee",
      "base": "",
      "fields": [{
          "name": "fee",
          "type": "asset"
        }
      ]
    },{
      "name": "modifyfee",
      "base": "",
      "fields": [{
          "name": "fee",
          "type": "asset"
        }
      ]
    },{
      "name": "addpair",
      "base": "",
      "fields": [{
          "name": "currency",
          "type": "asset"
        },{
          "name": "commodity",
          "type": "asset"
        }
      ]
    },{
      "name": "removepair",
      "base": "",
      "fields": [{
          "name": "currency",
          "type": "asset"
        },{
          "name": "commodity",
          "type": "asset"
        }
      ]
    }
  ],
  "actions": [{
      "name": "lock",
      "type": "lock",
      "ricardian_contract": ""
    },{
      "name": "unlock",
      "type": "unlock",
      "ricardian_contract": ""
    },{
      "name": "subbalance",
      "type": "subbalance",
      "ricardian_contract": ""
    },{
      "name": "sublocked",
      "type": "sublocked",
      "ricardian_contract": ""
    },{
      "name": "addbalance",
      "type": "addbalance",
      "ricardian_contract": ""
    },{
      "name": "lockx",
      "type": "lockx",
      "ricardian_contract": ""
    },{
      "name": "unlockx",
      "type": "unlockx",
      "ricardian_contract": ""
    },{
      "name": "sublockedx",
      "type": "sublockedx",
      "ricardian_contract": ""
    },{
      "name": "addbalancex",
      "type": "addbalancex",
      "ricardian_contract": ""
    },{
      "name": "createfee",
      "type": "createfee",
      "ricardian_contract": ""
    },{
      "name": "removefee",
      "type": "removefee",
      "ricardian_contract": ""
    },{
      "name": "modifyfee",
      "type": "modifyfee",
      "ricardian_contract": ""
    },{
      "name": "addpair",
      "type": "addpair",
      "ricardian_contract": ""
    },{
      "name": "removepair",
      "type": "removepair",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "accountasset",
      "index_type": "i64",
      "key_names": [
        "balance"
      ],
      "key_types": [
        "asset"
      ],
      "type": "account_asset"
    },{
      "name": "stat",
      "index_type": "i64",
      "key_names": [
        "supply"
      ],
      "key_types": [
        "asset"
      ],
      "type": "currency"
    },{
      "name": "fee",
      "index_type": "i64",
      "key_names": [
        "exchangefee"
      ],
      "key_types": [
        "asset"
      ],
      "type": "trading_fee"
    },{
      "name": "bankfee",
      "index_type": "i64",
      "key_names": [
        "bankfee"
      ],
      "key_types": [
        "asset"
      ],
      "type": "bank_fee"
    },{
      "name": "coin",
      "index_type": "i64",
      "key_names": [
        "currency"
      ],
      "key_types": [
        "symbol_code"
      ],
      "type": "CoinPair"
    },{
      "name": "cxprate",
      "index_type": "i64",
      "key_names": [
        "supply"
      ],
      "key_types": [
        "asset"
      ],
      "type": "cxp_rate"
    },{
      "name": "orderfee",
      "index_type": "i64",
      "key_names": [
        "orderid"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "order_fee"
    },{
      "name": "accfrozen",
      "index_type": "i64",
      "key_names": [
        "auto_key"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "acc_frozen"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
