const char* const tokenmap_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-08T08:04:27",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "tokenmap_s",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "tokenSymbol",
          "type": "uint64"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "contractaddr",
          "type": "string"
        },{
          "name": "symbol",
          "type": "uint64"
        }
      ]
    },{
      "name": "addpair",
      "base": "",
      "fields": [{
          "name": "token1",
          "type": "string"
        },{
          "name": "token2",
          "type": "string"
        },{
          "name": "addr",
          "type": "string"
        }
      ]
    },{
      "name": "oracle_rec",
      "base": "",
      "fields": [{
          "name": "username",
          "type": "name"
        }
      ]
    }
  ],
  "actions": [{
      "name": "addpair",
      "type": "addpair",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "tokens",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "tokenmap_s"
    },{
      "name": "oracles",
      "index_type": "i64",
      "key_names": [
        "username"
      ],
      "key_types": [
        "name"
      ],
      "type": "oracle_rec"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
