const char* const useraddress_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-08T08:04:05",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "tokenmap_s",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "tokenSymbol",
          "type": "uint64"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "contractaddr",
          "type": "string"
        },{
          "name": "symbol",
          "type": "uint64"
        }
      ]
    },{
      "name": "oracle_rec",
      "base": "",
      "fields": [{
          "name": "username",
          "type": "name"
        }
      ]
    },{
      "name": "acc",
      "base": "",
      "fields": [{
          "name": "name",
          "type": "name"
        },{
          "name": "addr",
          "type": "string"
        }
      ]
    },{
      "name": "currency",
      "base": "",
      "fields": [{
          "name": "supply",
          "type": "asset"
        }
      ]
    },{
      "name": "setaddr",
      "base": "",
      "fields": [{
          "name": "name",
          "type": "name"
        },{
          "name": "type",
          "type": "string"
        },{
          "name": "addr",
          "type": "string"
        }
      ]
    },{
      "name": "reqaddr",
      "base": "",
      "fields": [{
          "name": "name",
          "type": "name"
        },{
          "name": "type",
          "type": "string"
        }
      ]
    },{
      "name": "deposit",
      "base": "",
      "fields": [{
          "name": "addr",
          "type": "string"
        },{
          "name": "quantity",
          "type": "asset"
        },{
          "name": "tx",
          "type": "string"
        }
      ]
    },{
      "name": "reqwithdraw",
      "base": "",
      "fields": [{
          "name": "name",
          "type": "name"
        },{
          "name": "reqid",
          "type": "uint64"
        },{
          "name": "addr",
          "type": "string"
        },{
          "name": "quantity",
          "type": "asset"
        }
      ]
    }
  ],
  "actions": [{
      "name": "setaddr",
      "type": "setaddr",
      "ricardian_contract": ""
    },{
      "name": "reqaddr",
      "type": "reqaddr",
      "ricardian_contract": ""
    },{
      "name": "deposit",
      "type": "deposit",
      "ricardian_contract": ""
    },{
      "name": "reqwithdraw",
      "type": "reqwithdraw",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "tokens",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "tokenmap_s"
    },{
      "name": "oracles",
      "index_type": "i64",
      "key_names": [
        "username"
      ],
      "key_types": [
        "name"
      ],
      "type": "oracle_rec"
    },{
      "name": "table",
      "index_type": "i64",
      "key_names": [
        "name"
      ],
      "key_types": [
        "name"
      ],
      "type": "acc"
    },{
      "name": "stat",
      "index_type": "i64",
      "key_names": [
        "supply"
      ],
      "key_types": [
        "asset"
      ],
      "type": "currency"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
