const char* const withdraw_abi = R"=====(
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-11-08T08:03:24",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "tokenmap_s",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "tokenSymbol",
          "type": "uint64"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "contractaddr",
          "type": "string"
        },{
          "name": "symbol",
          "type": "uint64"
        }
      ]
    },{
      "name": "oracle_rec",
      "base": "",
      "fields": [{
          "name": "username",
          "type": "name"
        }
      ]
    },{
      "name": "errorbp",
      "base": "",
      "fields": [{
          "name": "node",
          "type": "name"
        },{
          "name": "errorcode",
          "type": "uint64"
        }
      ]
    },{
      "name": "tx_rec",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "reqid",
          "type": "uint64"
        },{
          "name": "user",
          "type": "name"
        },{
          "name": "to",
          "type": "string"
        },{
          "name": "quantity",
          "type": "asset"
        },{
          "name": "txhash",
          "type": "string"
        },{
          "name": "status",
          "type": "uint8"
        },{
          "name": "executor",
          "type": "name"
        },{
          "name": "blocknum",
          "type": "uint64"
        },{
          "name": "timestamp",
          "type": "uint64"
        },{
          "name": "validators",
          "type": "name[]"
        },{
          "name": "rejecters",
          "type": "errorbp[]"
        }
      ]
    },{
      "name": "request",
      "base": "",
      "fields": [{
          "name": "user",
          "type": "name"
        },{
          "name": "reqid",
          "type": "uint64"
        },{
          "name": "to",
          "type": "string"
        },{
          "name": "quantity",
          "type": "asset"
        },{
          "name": "is_internal_transfer",
          "type": "bool"
        }
      ]
    },{
      "name": "setexecutor",
      "base": "",
      "fields": [{
          "name": "bp",
          "type": "name"
        },{
          "name": "block_num",
          "type": "uint64"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "id",
          "type": "uint64"
        }
      ]
    },{
      "name": "setpending",
      "base": "",
      "fields": [{
          "name": "bp",
          "type": "name"
        },{
          "name": "token",
          "type": "string"
        },{
          "name": "id",
          "type": "uint64"
        }
      ]
    },{
      "name": "confirm",
      "base": "",
      "fields": [{
          "name": "validator",
          "type": "name"
        },{
          "name": "from",
          "type": "string"
        },{
          "name": "to",
          "type": "string"
        },{
          "name": "quantity",
          "type": "asset"
        },{
          "name": "txhash",
          "type": "string"
        }
      ]
    },{
      "name": "errorhandle",
      "base": "",
      "fields": [{
          "name": "rejecter",
          "type": "name"
        },{
          "name": "reqid",
          "type": "uint64"
        },{
          "name": "quantity",
          "type": "asset"
        },{
          "name": "to",
          "type": "string"
        },{
          "name": "txhash",
          "type": "string"
        },{
          "name": "errcode",
          "type": "uint64"
        }
      ]
    }
  ],
  "actions": [{
      "name": "request",
      "type": "request",
      "ricardian_contract": ""
    },{
      "name": "setexecutor",
      "type": "setexecutor",
      "ricardian_contract": ""
    },{
      "name": "setpending",
      "type": "setpending",
      "ricardian_contract": ""
    },{
      "name": "confirm",
      "type": "confirm",
      "ricardian_contract": ""
    },{
      "name": "errorhandle",
      "type": "errorhandle",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "tokens",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "tokenmap_s"
    },{
      "name": "oracles",
      "index_type": "i64",
      "key_names": [
        "username"
      ],
      "key_types": [
        "name"
      ],
      "type": "oracle_rec"
    },{
      "name": "withdrawals",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "tx_rec"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": [],
  "variants": []
})=====";
